### ISSUE TITLE
HD-Map Files Download

### ISSUE THREAD

**Issue by ziqipang** [argoai/argoverse2-api#3]
Hi Argo folks,

Thank you for your Argoverse 2.0 dataset! But I have a question related to the HD-Map part. In brief, I am wondering:

1. If the "Map Change" part corresponds to the "HD-Map" in Argoverse 1.1, and I should download it via "s3://argoai-argoverse/av2/tbv/"?
2. Since this time the HD-Map file is significantly larger than Argoverse 1.1, are they all needed for motion forecasting?

Best,

Ziqi

**Comment by James-Hays** [comment]
Hi Ziqi!

The "Map Change" or "TbV" dataset is an independent dataset. Each of the four datasets (sensor, lidar, motion forecasting, map change) have HD maps included. You don't need to download the Map Change dataset to use any other dataset. So for motion forecasting, you only need to download the ~60 GB worth of files to get the 250,000 scenarios and their HD maps.
